### ISSUE TITLE
item methods

### ISSUE THREAD

**Issue by spenk** [FallenMoonNetwork/CanaryLib#16]
im missing an method to get the item name
(item.getType.toString()) in old canary
also for damaged items me and dark wrote a piece for iAuction maby you could use it http://pastebin.com/Fv9BrkQY

item.setSlot(item,slot); doesnt work with parameter slot

also missing something like
player.swichworlds(world); player.swichdimension(dim); ?

**Comment by damagefilter** [comment]
Again Spenk, you as plugin dev are not supposed to use the switchWorlds method.
I'll make it private in the new CanaryPlayer class so there will be no confusion with this anymore.
In order to put a player in another world (that's also valid for the current b10.x) just make player.teleportTo(Location)
Where you specify the world name and dimension in Location before you send the player there.

**Comment by spenk** [comment]
i dont like it but i have to deal with it in that case =/
what about those other 2

**Comment by damagefilter** [comment]
setSlot(int) in Item is meant to set the inventory slot of said item not to set an item to a slot of an inventory that we don't have recollection of. With a lil bit of thinking you could of guessed that ;)
There's no way to get the item type though so I be adding this. 

Also: that you don't use switchWorlds is a convenient thing. You as plugin dev don't need to worry about the dimension a location is in to switch the worlds if needed. It'll be called when it's needed. Always. No worries.
